#!/bin/bash
#
# check_console
# By Kyle Anderson, 2011, under the GPL 2 License. 
#
# This nagios check to ensure that a workstation is always on a graphical terminal,
# even if X crashes. With sudo it tries to chvt's for you to fix it.
#
# Requires the following sudo rules to work properly:
# nagios ALL=(root) NOPASSWD: /usr/bin/fgconsole
# nagios ALL=(root) NOPASSWD: /usr/bin/chvt

# check for plugin directory where utils.sh lives
[ -d /usr/lib/nagios/plugins ]   && UTILPATH=/usr/lib/nagios/plugins
[ -d /usr/lib64/nagios/plugins ] && UTILPATH=/usr/lib64/nagios/plugins

#  load states and strings
if [ -x "$UTILPATH"/utils.sh ]; then
        . "$UTILPATH"/utils.sh
else
        echo "ERROR: Cannot find utils.sh"
        exit
fi

#The VT I am on now
CURRENTVT=`sudo fgconsole`

# The VT that has the lowest tty (probably gdm login)
GOODVT=`ps -ef | grep Xorg | tr " " "\n" | grep tty | sed 's/tty//g' | sort -g | head -n 1`

if ps -ef | grep Xorg | grep tty | awk '{ print $6 }' | grep -q tty$CURRENTVT ; then #Did the command run OK?
   echo "OK: There is an Xorg Process on the current VT"
   exit $STATE_OK
else
   echo "CRITICAL: There is no Xorg process on VT $CURRENTVT. Trying to Switch to $GOODVT"
   sudo chvt $GOODVT
   #If this works we won't go critical next time.
   exit $STATE_CRITICAL
fi
