#!/bin/bash
# 
# check_nfs_group_limit
# By Kyle Anderson, 2011, Under the GPL 2
#
# This checks to make sure that an nfs server doing more than 16 groups doesn't encounter the
# Next 1000 byte limit on group membership. See:
# https://xkyle.com/solving-the-nfs-16-group-limit-problem/

# check for plugin directory where utils.sh lives
[ -d /usr/lib/nagios/plugins ]   && UTILPATH=/usr/lib/nagios/plugins
[ -d /usr/lib64/nagios/plugins ] && UTILPATH=/usr/lib64/nagios/plugins


#  load states and strings
if [ -x "$UTILPATH"/utils.sh ]; then
        . "$UTILPATH"/utils.sh
else
        echo "ERROR: Cannot find utils.sh"
        exit
fi

OVERLIMIT=0
USERSOVER=""
for USER in `cat /proc/net/rpc/auth.unix.gid/content | grep -v "^#uid" | grep '#' | cut -f 2 -d " "`
do
	USERSOVER="$USER $USERSOVER"
	OVERLIMIT=1
done

if [ $OVERLIMIT -eq 0 ]; then # Is ffmpeg running?
   echo "OK: There are no users in the nfs gid cache that are past the 1000 byte limit"
   exit $STATE_OK
else
   echo "CRITICAL: There are users over the group limit: $USERSOVER "
   echo "Fix it and run date +%s > /proc/net/rpc/auth.unix.gid/flush to purge"
   exit $STATE_CRITICAL
fi
